version: '3.8'

services:
  ai-service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload 